## weaves

## GAM functions

require("mgcv")
require("car")
require("ggplot2")
require("grid")


## Some functions

hcc.chart <- function(gam1, ctr0="unknown", nocoef=FALSE, tbl=data0,
                      c0=c("value", "dt0"), name1="enqs") {

    ## Number of coefficients
    if (!nocoef) {
    l0 <- length(unique(gsub("\\.[0-9]+$", "", names(gam1$coefficients))))

    layout(matrix(1:l0, nrow = 1))
    plot(gam1)
    }

    x.df1 <- tbl
    if (is.null(tbl)) {
        x.df1 <- (gam1$model)[, 1, drop = FALSE]
        x.df1[, c0[[2]] ] <- rownames(x.df1)
        colnames(x.df1)[1] <- c0[1]
    } else {
        x.df1 <- tbl[, c0]
    }
    x.df1$type <- "Real"

    x.df2 <- data.frame(value = gam1$fitted.values, 
                        dt0 = x.df1[, c0[[2]] ] )
    x.df2$type <- "Fitted"

    datas <- rbind(x.df1, x.df2)

    ggplot(data = datas, aes(dt0, value, group = type, colour = type)) +
        geom_line(size = 0.8) +
        theme_bw() +
        labs(x = "date", y = name1,
             title = sprintf("Fit from GAM - %s", gam1[["name0"]]))

}

hcc.chart1 <- function(real0, fitted0, c0=c("value", "dt0"), 
                       name0="Predictions", name1="enqs") {

    x.df1 <- real0
    x.df1$type <- "Real"

    x.df2 <- fitted0
    x.df2$type <- "Predicted"

    datas <- rbind(x.df1, x.df2)

    ggplot(data = datas, aes(dt0, value, group = type, colour = type)) +
        geom_line(size = 0.8) +
        theme_bw() +
        labs(x = "date", y = name1,
             title = sprintf("Predictions from GAM - %s", name0))

}

hcc.gamS <- function(gam1, zz="all.Rout", force0=FALSE) {
    if (force0) {
        unlink(zz, force=force0)
        fl <- file(zz, "wt")
    }
    
    x.gam <- gam1
    zz <- file(zz, open = "at")
    sink(zz)
    cat("\n\n")
    cat(sprintf("start: %s", x.gam$name), "\n")
    ## what to look at: summary: EDF, p-values, R^2, GCV; AIC, magic
    cat("summary: ")
    print(summary(x.gam))

    cat("R^2: ", summary(x.gam)$r.sq, "; ")

    cat("GCV: ", summary(x.gam)$sp.criterion, "; ")

    cat("AIC: ", x.gam$aic, "; ")

    cat("BIC: ", BIC(x.gam))
    cat("\n")

    # sink(zz, type = "message")
    ## revert output back to the console -- only then access the file!
    ## sink(type = "message")
    sink()
    return(zz)
}

### Claims from Enquiries

## This is generated by 2csv. Joins in the weather.
## Not a big file.
data0 <- read.csv("out/xncas1.csv", stringsAsFactors=FALSE)

data0$dt0 <- as.POSIXct(data0$dt0)

## Generic classes for attributes
c0 <- colnames(data0)
idx <- which(grepl("^action1", c0)):which(grepl("^enqs", c0))
types <- c0[idx]

idx <- which(grepl("^tmax", c0)):which(grepl("^rain", c0))
wthrs <- c0[idx]

dtypes <- sapply(types, function(x) sprintf("d%s", x), USE.NAMES=FALSE)

dwthrs <- sapply(wthrs, function(x) sprintf("d%s", x), USE.NAMES=FALSE)

dts <- c("mm1")

## Just to check
xcld <- c(types, wthrs, dtypes, dwthrs, dts)
xcld <- setdiff(colnames(data0), xcld)
xcld
